# Generated by Django 5.2.3 on 2025-07-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_varified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
