# Generated by Django 5.2.3 on 2025-07-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_activity_post_datetime_post_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
